---

- name: "Configure SSSD's Memory Cache to Expire"
  ini_file:
    dest: /etc/sssd/sssd.conf
    section: nss
    option: memcache_timeout
    value: "{{ services_sssd_memcache_timeout }}"
    create: yes
  tags:
    - CCE-80364-3
    - NIST-800-53-IA-5(10)
    - NIST-800-53-IA-5(13)

- name: "Configure SSSD to Expire SSH Known Hosts"
  ini_file:
    dest: /etc/sssd/sssd.conf
    section: ssh
    option: ssh_known_hosts_timeout
    value: "{{ services_sssd_ssh_known_hosts_timeout }}"
    create: yes
  tags:
    - CCE-80366-8
    - NIST-800-53-IA-5(13)

- name: "Configure SSD to Expire Offline Credentials"
  ini_file:
    dest: /etc/sssd/sssd.conf
    section: pam
    option: offline_credentials_expiration
    value: "{{ services_sssd_offline_credentials_expiration }}"
    create: yes
  tags:
    - CCE-80365-0
    - NIST-800-53-IA-5(13)
