---

- name: "Disable SSH Support for User Known Hosts"
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?IgnoreUserKnownHosts'
    line: "IgnoreUserKnownHosts yes"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-80372-6
    - NIST-800-53-AC-17(b)
    - NIST-800-53-CM-6(a)
    - NIST-800-171-3.1.12
    - DISA-STIG-RHEL-07-040380

- name: Disable SSH Access via Empty Passwords
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?PermitEmptyPasswords'
    line: "PermitEmptyPasswords no"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-27471-2
    - NIST-800-53-AC-3
    - NIST-800-53-AC-6
    - NIST-800-53-AC-17(b)
    - NIST-800-53-CM-6(b)
    - NIST-800-171-3.1.1
    - NIST-800-171-3.1.5
    - DISA-STIG-RHEL-07-010300

- name: Set SSH Client Alive Count
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?ClientAliveCountMax'
    line: "ClientAliveCountMax {{ services_ssh_server_sshd_set_keepalive }}"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-27082-7
    - NIST-800-53-AC-2(5)
    - NIST-800-53-SA-8
    - NIST-800-53-AC-12
    - NIST-800-53-AC-17(b)
    - NIST-800-171-3.1.11
    - DISA-STIG-RHEL-07-040340

- name: Set SSH Idle Timeout Interval
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?ClientAliveInterval'
    line: "ClientAliveInterval {{ services_ssh_server_sshd_idle_timeout_value }}"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-27433-2
    - NIST-800-53-AC-2(5)
    - NIST-800-53-SA-8(i)
    - NIST-800-53-AC-12
    - NIST-800-53-AC-17(b)
    - NIST-800-171-3.1.11
    - DISA-STIG-RHEL-07-040320

- name: Enable SSH Warning Banner
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?Banner'
    line: "Banner /etc/issue"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-27314-4
    - NIST-800-53-AC-8(a)
    - NIST-800-53-AC-8(b)
    - NIST-800-53-AC-8(c)(1)
    - NIST-800-53-AC-8(c)(2)
    - NIST-800-53-AC-8(c)(3)
    - NIST-800-53-AC-17(b)
    - NIST-800-171-3.1.9
    - DISA-STIG-RHEL-07-040170

- name: "Use Only Approved MACs"
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?MACs'
    line: "MACs {{ services_ssh_server_sshd_approved_macs }}"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-27455-5
    - NIST-800-53-AC-17(b)
    - NIST-800-53-AC-17(2)
    - NIST-800-53-IA-7
    - NIST-800-53-SC-13
    - NIST-800-171-3.1.13
    - NIST-800-171-3.13.11
    - NIST-800-171-3.13.8
    - DISA-STIG-RHEL-07-040400

- name: Do Not Allow SSH Environment Options
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?PermitUserEnvironment'
    line: "PermitUserEnvironment no"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-27363-1
    - NIST-800-53-AC-17(b)
    - NIST-800-53-CM-6(b)
    - NIST-800-171-3.1.12
    - DISA-STIG-RHEL-07-010460

- name: "Disable Kerberos Authentication"
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?kerberosauthentication'
    line: "KerberosAuthentication no"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-80221-5
    - NIST-800-53-CM-6(c)
    - NIST-800-171-3.1.12
    - DISA-STIG-RHEL-07-040440

- name: "Allow Only SSH Protocol 2"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?Protocol [0-9]'
    line: "Protocol 2"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-27320-1
    - NIST-800-53-AC-17(b)
    - NIST-800-53-AC-17(8).1(ii)
    - NIST-800-53-IA-5(1)(c)
    - NIST-800-171-3.1.13
    - NIST-800-171-3.5.4
    - DISA-STIG-RHEL-07-040390

- name: Disable SSH Support for .rhosts Files
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?IgnoreRhosts'
    line: "IgnoreRhosts yes"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-27377-1
    - NIST-800-53-AC-3
    - NIST-800-53-AC-17(b)
    - NIST-800-53-CM-6(a)
    - NIST-800-171-3.1.12
    - DISA-STIG-RHEL-07-040350

- name: Disable SSH Support for Rhosts RSA Authentication
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?RhostsRSAAuthentication'
    line: "RhostsRSAAuthentication no"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-80373-4
    - NIST-800-53-CM-6(a)
    - NIST-800-53-AC-17(b)
    - NIST-800-171-3.1.12
    - DISA-STIG-RHEL-07-040330

- name: Enable Encrypted X11 Forwarding
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?X11Forwarding'
    line: "X11Forwarding yes"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-80226-4
    - NIST-800-53-CM-2(1)(b)
    - NIST-800-171-3.1.13
    - DISA-STIG-RHEL-07-040710

- name: Use Only Approved Ciphers
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?Ciphers'
    line: "Ciphers {{ services_ssh_server_sshd_approved_ciphers }}"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-27295-5
    - NIST-800-53-AC-3
    - NIST-800-53-AC-17(b)
    - NIST-800-53-AC-17(2)
    - NIST-800-53-AU-10(5)
    - NIST-800-53-CM-6(b)
    - NIST-800-53-IA-5(1)(c)
    - NIST-800-53-IA-7
    - NIST-800-53-SI-7
    - NIST-800-171-3.1.13
    - NIST-800-171-3.13.11
    - NIST-800-171-3.13.8
    - DISA-STIG-RHEL-07-040110

- name: Disable Host-Based Authentication
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?HostbasedAuthentication'
    line: "HostbasedAuthentication no"
  tags:
    - CCE-27413-4
    - NIST-800-53-AC-3
    - NIST-800-53-AC-17
    - NIST-800-53-CM-6(b)
    - NIST-800-171-3.1.12
    - DISA-STIG-RHEL-07-010470

- name: "Enable Use of Strict Mode Checking"
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?StrictModes'
    line: "StrictModes yes"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-80222-3
    - NIST-800-53-AC-6
    - NIST-800-53-AC-17(b)
    - NIST-800-171-3.1.12
    - DISA-STIG-RHEL-07-040450

- name: "Enable use of Privilege Separation"
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?useprivilegeseparation'
    line: "UsePrivilegeSeparation sandbox"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-80223-1
    - NIST-800-53-AC-6
    - NIST-800-53-AC-17(b)
    - NIST-800-171-3.1.12
    - DISA-STIG-RHEL-07-040460

- name: "Disable GSSAPI Authentication"
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?gssapiauthentication'
    line: "GSSAPIAuthentication no"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-80220-7
    - NIST-800-53-AC-17(b)
    - NIST-800-53-CM-6(c)
    - NIST-800-171-3.1.12
    - DISA-STIG-RHEL-07-040430

- name: "Disable Compression or Set Compression to delayed"
  lineinfile:
    create: yes
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#?Compression'
    line: "Compression delayed"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-80224-9
    - NIST-800-53-CM-6(b)
    - NIST-800-171-3.1.12
    - DISA-STIG-RHEL-07-040470

- name: "Disable SSH Root Login"
  lineinfile:
    create: yes
    path: "/etc/ssh/sshd_config"
    regexp: "(?i)^#?PermitRootLogin"
    line: "PermitRootLogin no"
    insertafter: '(?i)^#? Authentication'
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
  tags:
    - CCE-27445-6
    - NIST-800-53-AC-3
    - NIST-800-53-AC-6(2)
    - NIST-800-53-AC-17(b)
    - NIST-800-53-IA-2
    - NIST-800-53-IA-2(5)
    - NIST-800-171-3.1.1
    - NIST-800-171-3.1.5
    - DISA-STIG-RHEL-07-040370

- name: Verify Permissions on SSH Server Public .pub Key Files - Find /etc/ssh file(s)
  find:
    paths: "/etc/ssh"
    patterns: "^.*.pub$"
  check_mode: no
  register: ssh_server_public_keys_found
  tags:
    - CCE-27311-0
    - NIST-800-53-AC-6
    - NIST-800-171-3.1.13
    - NIST-800-171-3.13.10
    - DISA-STIG-RHEL-07-040410

- name: Verify Permissions on SSH Server Public .pub Key Files - Set permissions for any Files Found
  file:
    path: "{{ item.path }}"
    mode: 0644
  loop: "{{ ssh_server_public_keys_found.files }}"
  when: ssh_server_public_keys_found is defined
  tags:
    - CCE-27311-0
    - NIST-800-53-AC-6
    - NIST-800-171-3.1.13
    - NIST-800-171-3.13.10
    - DISA-STIG-RHEL-07-040410

- name: Verify Permissions of SSH Server Private _key Key files -  Find /etc/ssh file(s)
  find:
    paths: "/etc/ssh"
    patterns: "^.*_key$"
  check_mode: no
  register: ssh_server_private_keys_found
  tags:
    - CCE-27485-2
    - NIST-800-53-AC-6
    - NIST-800-53-AC-17
    - NIST-800-171-3.1.13
    - NIST-800-171-3.13.10
    - DISA-STIG-RHEL-07-040420

- name: Verify Permissions of SSH Server Private _key Key files - Set permissions for any Files Found
  file:
    path: "{{ item.path }}"
    mode: 0640
  loop: "{{ ssh_server_private_keys_found.files }}"
  when: ssh_server_private_keys_found is defined
  tags:
    - CCE-27485-2
    - NIST-800-53-AC-6
    - NIST-800-53-AC-17
    - NIST-800-171-3.1.13
    - NIST-800-171-3.13.10
    - DISA-STIG-RHEL-07-040420

- name: Enable SSHD in firewalld (default port)
  firewalld:
    service: ssh
    permanent: yes
    state: enabled
  tags:
    - CCE-80361-9
    - NIST-800-53-AC-17(a)
    - NIST-800-171-3.1.12
