---
#Start Set Password Hashing Algorithm Tasks
- name: Set Password Hashing Algorithm in /etc/login.defs
  lineinfile:
      dest: /etc/login.defs
      regexp: '^#?ENCRYPT_METHOD'
      line: "ENCRYPT_METHOD\tSHA512"
      state: present
  tags:
    - CCE-27124-7
    - NIST-800-53-IA-5(b)
    - NIST-800-53-IA-5(c)
    - NIST-800-53-IA-5(1)(c)
    - NIST-800-53-IA-7
    - NIST-800-171-3.13.11
    - DISA-STIG-RHEL-07-010210

- name: Set Password Hashing Algorithm in /etc/libuser.conf
  ini_file:
    dest: /etc/libuser.conf
    section: defaults
    option: crypt_style
    value: sha512
    state: present
  tags:
    - CCE-27053-8
    - NIST-800-53-IA-5(b)
    - NIST-800-53-IA-5(c)
    - NIST-800-53-IA-5(1)(c)
    - NIST-800-53-IA-7
    - NIST-800-171-3.13.11
    - DISA-STIG-RHEL-07-010220

- name: Set PAM's Password Hashing Algorithm
  pamd:
    name: "{{ item }}"
    type: password
    control: sufficient
    module_path: pam_unix.so
    module_arguments: 'sha512'
    state: args_present
  loop:
    - system-auth
    - password-auth
  tags:
    - CCE-27104-9
    - NIST-800-53-IA-5(b)
    - NIST-800-53-IA-5(c)
    - NIST-800-53-IA-5(1)(c)
    - NIST-800-53-IA-7
    - NIST-800-171-3.13.11
    - DISA-STIG-RHEL-07-010220

#End Set Password Hashing Algorithm Tasks
#Start Set Lockouts for Failed Password Attempts Tasks
- name: Ensure 'auth required pam_faillock' before pam_unix.so
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: required
    new_module_path: pam_faillock.so
    state: before
  loop:
    - system-auth
    - password-auth
  tags:
    - CCE-80353-6
    - CCE-26884-7
    - CCE-27297-1
    - CCE-27350-8
    - NIST-800-53-AC-7(b)
    - NIST-800-171-3.1.8
    - DISA-STIG-RHEL-07-010320
    - DISA-STIG-RHEL-07-010330

- name: Ensure correct arguments are present for 'auth required pam_faillock' before pam_unix.so
  pamd:
    name: "{{ item }}"
    type: auth
    control: required
    module_path: pam_faillock.so
    module_arguments: 'preauth
        silent
        even_deny_root
        unlock_time=never
        fail_interval=900
        deny=3'
    state: args_present
  loop:
    - system-auth
    - password-auth
  tags:
    - CCE-80353-6
    - CCE-26884-7
    - CCE-27297-1
    - CCE-27350-8
    - NIST-800-53-AC-7(b)
    - NIST-800-171-3.1.8
    - DISA-STIG-RHEL-07-010320
    - DISA-STIG-RHEL-07-010330

- name: Ensure 'auth [default=die] pam_faillock' before pam_deny.so
  pamd:
    name: "{{ item }}"
    type: auth
    control: required
    module_path: pam_deny.so
    new_type: auth
    new_control: '[default=die]'
    new_module_path: pam_faillock.so
    module_arguments: 'authfail'
    state: before
  loop:
    - system-auth
    - password-auth
  tags:
    - CCE-80353-6
    - CCE-26884-7
    - CCE-27297-1
    - CCE-27350-8
    - NIST-800-53-AC-7(b)
    - NIST-800-171-3.1.8
    - DISA-STIG-RHEL-07-010320
    - DISA-STIG-RHEL-07-010330

- name: Ensure correct arguments are present for 'auth [default=die] pam_faillock' before pam_deny.so
  pamd:
    name: "{{ item }}"
    type: auth
    control: '[default=die]'
    module_path: pam_faillock.so
    module_arguments: 'authfail
        silent
        even_deny_root
        unlock_time=never
        fail_interval=900
        deny=3'
    state: args_present
  loop:
    - system-auth
    - password-auth
  tags:
    - CCE-80353-6
    - CCE-26884-7
    - CCE-27297-1
    - CCE-27350-8
    - NIST-800-53-AC-7(b)
    - NIST-800-171-3.1.8
    - DISA-STIG-RHEL-07-010320
    - DISA-STIG-RHEL-07-010330

- name: Ensure 'account required pam_faillock' before pam_unix.so
  pamd:
    name: "{{ item }}"
    type: account
    control: required
    module_path: pam_unix.so
    new_type: account
    new_control: required
    new_module_path: pam_faillock.so
    state: before
  loop:
    - system-auth
    - password-auth
  tags:
    - CCE-80353-6
    - NIST-800-53-AC-7(b)
    - DISA-STIG-RHEL-07-010330

- name: "Do not allow users to reuse recent passwords - system-auth"
  pamd:
    name: system-auth
    type: password
    control: sufficient
    module_path: pam_unix.so
    module_arguments: 'remember=5'
    state: args_present
  tags:
    - CCE-26923-3
    - NIST-800-53-IA-5(f)
    - NIST-800-53-IA-5(1)(e)
    - NIST-800-171-3.5.8
    - DISA-STIG-RHEL-07-010270

#End Set Lockouts for Failed Password Attempts Tasks
#Start Set Password Quality Requirements Tasks
- name: Ensure PAM variable minlen is set accordingly
  lineinfile:
    create: yes
    path: "/etc/security/pwquality.conf"
    regexp: '^#?\s*minlen'
    line: "minlen = {{ system_settings_account_and_access_control_password_pam_minlen }}"
  tags:
    - CCE-27293-0
    - NIST-800-53-IA-5(1)(a)
    - DISA-STIG-RHEL-07-010280

- name: Ensure PAM variable maxclassrepeat is set accordingly
  lineinfile:
    create: yes
    path: "/etc/security/pwquality.conf"
    regexp: '^#?\s*maxclassrepeat'
    line: "maxclassrepeat = {{ system_settings_account_and_access_control_password_pam_maxclassrepeat }}"
  tags:
    - CCE-27512-3
    - NIST-800-53-IA-5
    - NIST-800-53-IA-5(c)
    - DISA-STIG-RHEL-07-010190

- name: Ensure PAM variable dcredit is set accordingly
  lineinfile:
    create: yes
    path: "/etc/security/pwquality.conf"
    regexp: '^#?\s*dcredit'
    line: "dcredit = {{ system_settings_account_and_access_control_password_pam_dcredit }}"
  tags:
    - CCE-27214-6
    - NIST-800-53-IA-5(1)(a)
    - NIST-800-53-IA-5(b)
    - NIST-800-53-IA-5(c)
    - NIST-800-53-194
    - DISA-STIG-RHEL-07-010140

- name: Ensure PAM variable minclass is set accordingly
  lineinfile:
    create: yes
    path: "/etc/security/pwquality.conf"
    regexp: '^#?\s*minclass'
    line: "minclass = {{ system_settings_account_and_access_control_password_pam_minclass }}"
  tags:
    - CCE-27115-5
    - NIST-800-53-IA-5
    - DISA-STIG-RHEL-07-010170

- name: Ensure PAM variable difok is set accordingly
  lineinfile:
    create: yes
    path: "/etc/security/pwquality.conf"
    regexp: '^#?\s*difok'
    line: "difok = {{ system_settings_account_and_access_control_password_pam_difok }}"
  tags:
    - CCE-26631-2
    - NIST-800-53-IA-5(b)
    - NIST-800-53-IA-5(c)
    - NIST-800-53-IA-5(1)(b)
    - DISA-STIG-RHEL-07-010160

- name: Ensure PAM variable ocredit is set accordingly
  lineinfile:
    create: yes
    path: "/etc/security/pwquality.conf"
    regexp: '^#?\s*ocredit'
    line: "ocredit = {{ system_settings_account_and_access_control_password_pam_ocredit }}"
  tags:
    - CCE-27360-7
    - NIST-800-53-IA-5(b)
    - NIST-800-53-IA-5(c)
    - NIST-800-53-IA-5(1)(a)
    - DISA-STIG-RHEL-07-010150

- name: Ensure PAM variable lcredit is set accordingly
  lineinfile:
    create: yes
    path: "/etc/security/pwquality.conf"
    regexp: '^#?\s*lcredit'
    line: "lcredit = {{ system_settings_account_and_access_control_password_pam_lcredit }}"
  tags:
    - CCE-27345-8
    - NIST-800-53-IA-5(b)
    - NIST-800-53-IA-5(c)
    - NIST-800-53-IA-5(1)(a)
    - DISA-STIG-RHEL-07-010130

- name: Ensure PAM variable ucredit is set accordingly
  lineinfile:
    create: yes
    path: "/etc/security/pwquality.conf"
    regexp: '^#?\s*ucredit'
    line: "ucredit = {{ system_settings_account_and_access_control_password_pam_ucredit }}"
  tags:
    - CCE-27200-5
    - NIST-800-53-IA-5(b)
    - NIST-800-53-IA-5(c)
    - NIST-800-53-IA-5(1)(a)
    - DISA-STIG-RHEL-07-010120

- name: Ensure correct retry argument present for 'password requisite pam_pwquality.so' - system-auth
  pamd:
    name: system-auth
    type: password
    control: requisite
    module_path: pam_pwquality.so
    module_arguments: 'retry=3'
    state: args_present
  tags:
    - CCE-27160-1
    - NIST-800-53-CM-6(b)
    - NIST-800-53-IA-5(c)
    - DISA-STIG-RHEL-07-010119
#End Set Password Quality Requirements Tasks
#Start Set Last Logon/Access Motification Tasks
- name: Ensure 'session [default=1] pam_lastlog.so' exists - postlogin
  pamd:
    name: postlogin
    type: session
    control: '[success=1 default=ignore]'
    module_path: pam_succeed_if.so
    new_type: session
    new_control: '[default=1]'
    new_module_path: pam_lastlog.so
    state: after
  tags:
    - CCE-27275-7
    - NIST-800-53-AC-9
    - DISA-STIG-RHEL-07-040530

- name: Ensure correct arguments for 'session [default=1] pam_lastlog.so' - postlogin
  pamd:
    name: postlogin
    type: session
    control: '[default=1]'
    module_path: pam_lastlog.so
    module_arguments: 'nowtmp
        showfailed'
    state: args_present
  tags:
    - CCE-27275-7
    - NIST-800-53-AC-9
    - DISA-STIG-RHEL-07-040530

- name: Ensure 'session optional pam_lastlog.so' exists - postlogin
  pamd:
    name: postlogin
    type: session
    control: '[default=1]'
    module_path: pam_lastlog.so
    new_type: session
    new_control: optional
    new_module_path: pam_lastlog.so
    state: after
  tags:
    - CCE-27275-7
    - NIST-800-53-AC-9
    - DISA-STIG-RHEL-07-040530

- name: Ensure correct arguments for 'session optional pam_lastlog.so' - postlogin
  pamd:
    name: postlogin
    type: session
    control: 'optional'
    module_path: pam_lastlog.so
    module_arguments: 'silent
        noupdate
        showfailed'
    state: args_present
  tags:
    - CCE-27275-7
    - NIST-800-53-AC-9
    - DISA-STIG-RHEL-07-040530
#End Set Last Logon/Access Motification Tasks

#Configure Console Screen Locking
- name: Ensure screen package is installed
  package:
    name: screen
    state: present
  tags:
    - CCE-27351-6
    - NIST-800-53-AC-11(a)
    - NIST-800-171-3.1.10
    - DISA-STIG-RHEL-07-010090

#Skipping Hardware Tokens for Authentication
#Skipping Require Authentication for Single User Mode

- name: Disable Ctrl-Alt-Del Burst Action
  lineinfile:
    path: /etc/systemd/system.conf
    state: present
    regexp: '^CtrlAltDelBurstAction'
    line: "CtrlAltDelBurstAction=none"
  tags:
    - CCE-80449-2
    - NIST-800-53-AC-6
    - NIST-800-171-3.4.5

- name: Verify that Interactive Boot is Disabled in /etc/default/grub
  replace:
    path: /etc/default/grub
    regexp: 'systemd.confirm_spawn=(1|yes|true|on)'
    replace: "systemd.confirm_spawn=no"
  tags:
    - CCE-27335-9
    - NIST-800-53-SC-2
    - NIST-800-53-AC-3
    - NIST-800-171-3.1.2
    - NIST-800-171-3.4.5

- name: Check if Interactive Boot is Enabled (runtime)
  shell: |
    /sbin/grubby --info=ALL
  register: grubby_info
  changed_when: no
  check_mode: no
  tags:
    - CCE-27335-9
    - NIST-800-53-SC-2
    - NIST-800-53-AC-3
    - NIST-800-171-3.1.2
    - NIST-800-171-3.4.5

- name: Disable Interactive Boot when Enabled (runtime)
  command: |
    /sbin/grubby --update-kernel=ALL --remove-args="systemd.confirm_spawn"
  when:
    - grubby_info is defined
    - ("systemd.confirm_spawn=yes" in grubby_info.stdout) or ("systemd.confirm_spawn=1" in grubby_info.stdout) or ("systemd.confirm_spawn=on" in grubby_info.stdout) or ("systemd.confirm_spawn=true" in grubby_info.stdout)
  tags:
    - CCE-27335-9
    - NIST-800-53-SC-2
    - NIST-800-53-AC-3
    - NIST-800-171-3.1.2
    - NIST-800-171-3.4.5

- name: Disable Ctrl-Alt-Del Reboot Activation
  systemd:
    name: ctrl-alt-del.target
    masked: yes
  tags:
    - CCE-27511-5
    - NIST-800-53-AC-6
    - NIST-800-171-3.4.5
    - DISA-STIG-RHEL-07-020230

- name: Disable service debug-shell
  service:
    name: debug-shell
    state: stopped
    enabled: no
  register: service_result
  failed_when: "service_result is failed and ('Could not find the requested service' not in service_result.msg)"
  tags:
    - CCE-80206-6
    - NIST-800-171-3.4.5

- name: Disable socket of service debug-shell if applicable
  service:
    name: debug-shell.socket
    state: stopped
    enabled: no
  register: socket_result
  failed_when: "socket_result is failed and ('Could not find the requested service' not in socket_result.msg)"
  tags:
    - CCE-80206-6
    - NIST-800-171-3.4.5

#Start Secure Session Configuration Files for Login Accounts Tasks
- name: Ensure the Default UMASK is Set Correctly in login.defs
  lineinfile:
    create: yes
    path: /etc/login.defs
    regexp: '^#?UMASK'
    line: "UMASK\t{{ system_settings_account_and_access_control_user_umask }}"
  tags:
    - CCE-80205-8
    - NIST-800-53-CM-6(b)
    - NIST-800-53-SA-8
    - DISA-STIG-RHEL-07-020240

- name: Set Interactive Session Timeout
  lineinfile:
    create: yes
    path: /etc/profile
    regexp: '^#?TMOUT'
    line: "TMOUT={{ system_settings_account_and_access_control_accounts_tmout }}"
  tags:
    - CCE-27557-8
    - NIST-800-53-AC-12
    - NIST-800-53-SC-10
    - NIST-800-171-3.1.11
    - DISA-STIG-RHEL-07-040160

- name: Ensure Logon Failure Delay is Set Correctly in login.defs
  lineinfile:
    dest: /etc/login.defs
    regexp: '^#?FAIL_DELAY'
    line: "FAIL_DELAY\t{{ system_settings_account_and_access_control_accounts_fail_delay }}"
  tags:
    - CCE-80352-8
    - NIST-800-53-AC-7(b)
    - NIST-800-53-CM-6(b)
    - DISA-STIG-RHEL-07-010430

- name: Limit the Number of Concurrent Login Sessions Allowed Per User
  lineinfile:
    state: present
    path: /etc/security/limits.conf
    insertbefore: '^# End of file'
    regexp: '^#?\*.*maxlogins'
    line: "*        hard    maxlogins       {{ system_settings_account_and_access_control_accounts_max_concurrent_login_sessions }}"
  tags:
    - CCE-27081-9
    - NIST-800-53-AC-10
    - DISA-STIG-RHEL-07-040000

#End Secure Session Configuration Files for Login Accounts Tasks
#Skipping GUI Banner

- name: Modify the System Login Banner
  copy:
    src: files/banner
    dest: /etc/issue
    owner: root
    group: root
    mode: 0644
  tags:
    - CCE-27303-7
    - NIST-800-53-AC-8(a)
    - NIST-800-53-AC-8(b)
    - NIST-800-53-AC-8(c)(1)
    - NIST-800-53-AC-8(c)(2)
    - NIST-800-53-AC-8(c)(3)
    - NIST-800-171-3.1.11
    - DISA-STIG-RHEL-07-010050

#Start Protect Accounts by Restricting Password-Based Login Tasks
#Start Set Password Expiration Parameters

- name: Set Password Minimum Length in login.defs
  lineinfile:
    state: present
    path: /etc/login.defs
    regexp: '^PASS_MIN_LEN'
    line: "PASS_MIN_LEN\t{{ system_settings_account_and_access_control_accounts_password_minlen_login_defs }}"
  tags:
    - CCE-27123-9
    - NIST-800-53-IA-5(f)
    - NIST-800-53-IA-5(1)(a)
    - NIST-800-171-3.5.7

- name: Set Password Warning Age
  lineinfile:
    state: present
    path: /etc/login.defs
    regexp: '^PASS_WARN_AGE'
    line: "PASS_WARN_AGE\t{{ system_settings_account_and_access_control_accounts_password_warn_age_login_defs }}"
  tags:
    - CCE-26486-1
    - NIST-800-53-AC-2(2)
    - NIST-800-53-IA-5(f)
    - NIST-800-171-3.5.8

- name: Set Password Minimum Age
  lineinfile:
    state: present
    path: /etc/login.defs
    regexp: '^PASS_MIN_DAYS'
    line: "PASS_MIN_DAYS\t{{ system_settings_account_and_access_control_accounts_password_minimum_age_login_defs }}"
  tags:
    - CCE-27002-5
    - NIST-800-53-IA-5(f)
    - NIST-800-53-IA-5(1)(d)
    - NIST-800-171-3.5.8
    - DISA-STIG-RHEL-07-010230

- name: Set Password Maximum Age
  lineinfile:
    state: present
    path: /etc/login.defs
    regexp: '^PASS_MAX_DAYS'
    line: "PASS_MAX_DAYS\t{{ system_settings_account_and_access_control_accounts_password_maximum_age_login_defs }}"
  tags:
    - CCE-27051-2
    - NIST-800-53-IA-5(f)
    - NIST-800-53-IA-5(g)
    - NIST-800-53-IA-5(1)(d)
    - NIST-800-171-3.5.6
    - DISA-STIG-RHEL-07-010250
