---

- name: Disable Automatic IPv6 Configuration
  lineinfile:
    path: "/etc/sysconfig/network-scripts/ifcfg-{{ item }}"
    regexp: '(?i)^#?IPV6_AUTOCONF'
    line: "IPV6_AUTOCONF=no"
  loop: "{{ ansible_interfaces }}"
  when: system_settings_network_configuration_and_firewalls_disable_ipv6_autoconf

- name: Configure Networking Kernel Parameters - IPv4 & IPv6
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
    sysctl_set: "{{ item.sysctl_set }}"
    reload: "{{ item.reload }}"
  loop: "{{ system_settings_network_configuration_and_firewalls_sysctl_config }}"
  tags:
    - CCE-80179-5
    - CCE-80335-1
    - CCE-80356-9
    - CCE-80182-9
    - CCE-80183-7
    - CCE-80180-3
    - CCE-80181-1
    - CCE-80175-3
    - CCE-80162-1
    - CCE-80166-2
    - CCE-80163-9
    - CCE-80168-8
    - CCE-80159-7
    - CCE-27434-0
    - CCE-27495-1
    - CCE-80158-9
    - CCE-80160-5
    - CCE-80167-0
    - CCE-80165-4
    - CCE-80164-7
    - CCE-80161-3
    - CCE-80156-3
    - NIST-800-53-AC-4
    - NIST-800-53-AC-17(7)
    - NIST-800-53-CM-7
    - NIST-800-53-SC-5
    - NIST-800-53-SC-7
    - NIST-800-171-3.1.20
    - DISA-STIG-RHEL-07-040830
    - DISA-STIG-RHEL-07-040620
    - DISA-STIG-RHEL-07-040640
    - DISA-STIG-RHEL-07-040610
    - DISA-STIG-RHEL-07-040641
    - DISA-STIG-RHEL-07-040630
    - DISA-STIG-RHEL-07-040660
    - DISA-STIG-RHEL-07-040650


- name: Use Privacy Extensions for Automatic Generation of IPv6 Addresses
  lineinfile:
    path: "/etc/sysconfig/network-scripts/ifcfg-{{ item }}"
    regexp: '(?i)^#?IPV6_PRIVACY'
    line: "IPV6_PRIVACY=rfc3041"
  loop: "{{ ansible_interfaces }}"
  when: system_settings_network_configuration_and_firewalls_ipv6_privacy
  tags:
    - CCE-80185-2
    - NIST-800-53-CM-7
    - NIST-800-171-3.1.20

- name: Enable SSHD in firewalld (default port)
  firewalld:
    immediate: yes
    permanent: yes
    service: ssh
    state: enabled
    zone: drop
  tags:
    - CCE-80361-9
    - NIST-800-53-AC-17(a)
    - NIST-800-171-3.1.12

- name: Set Default firewalld Zone for Incoming Packets
  lineinfile:
    path: "/etc/firewalld/firewalld.conf"
    regexp: '^DefaultZone'
    line: "DefaultZone=drop"
  notify: restart firewalld
  tags:
  - CCE-27349-0
  - NIST-800-53-CM-6(b)
  - NIST-800-53-CM-7
  - NIST-800-171-3.1.3
  - NIST-800-171-3.4.7
  - NIST-800-171-3.13.6
  - DISA-STIG-RHEL-07-040810

- name: Verify firewalld Service is Started and Enabled
  service:
    name: firewalld
    enabled: yes
    state: started
  tags:
    - CCE-27361-5
    - NIST-800-53-CM-6(b)
    - NIST-800-171-3.1.3
    - NIST-800-171-3.4.7
    - DISA-STIG-RHEL-07-040520
