---

- name: Verify and Correct File Permissions with RPM - Get list of files with incorrect permissions
  shell: |
    rpm -Va --nofiledigest | awk '{ if (substr($0,2,1)=="M") print $NF }'
  args:
    warn: False # Ignore ANSIBLE0006, we can't fetch files with incorrect permissions using rpm module
  register: rpm_files_with_incorrect_permissions
#  failed_when: False
  changed_when: False
  check_mode: no
  tags:
    - CCE-27209-6
    - NIST-800-53-AC-6
    - NIST-800-53-AU-9(1)
    - NIST-800-53-AU-9(3)
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)
    - NIST-800-171-3.3.8
    - NIST-800-171-3.4.1
    - DISA-STIG-RHEL-07-010010

- name: Verify and Correct File Permissions with RPM - Correct file permissions with RPM
  shell: |
    rpm --setperms $(rpm -qf '{{ item }}')
  args:
    warn: False # Ignore ANSIBLE0006, we can't correct permissions using rpm module
  loop: "{{ rpm_files_with_incorrect_permissions.stdout_lines }}"
  when:
    - rpm_files_with_incorrect_permissions.stdout_lines is defined
    - (rpm_files_with_incorrect_permissions.stdout_lines | length > 0)
    - "'/var/log/dmesg' not in rpm_files_with_incorrect_permissions.stdout_lines" # Workaround for bug found at https://bugzilla.redhat.com/show_bug.cgi?id=1584317
  tags:
    - CCE-27209-6
    - NIST-800-53-AC-6
    - NIST-800-53-AU-9(1)
    - NIST-800-53-AU-9(3)
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)
    - NIST-800-171-3.3.8
    - NIST-800-171-3.4.1
    - DISA-STIG-RHEL-07-010010

- name: Verify File Hashes with RPM - Get List of Files with Incorrect Hash
  shell: |
    rpm -Va | grep -E '^..5.* /(bin|sbin|lib|lib64|usr)/' | awk '{print $NF}'
  args:
    warn: False # Ignore ANSIBLE0006, we can't fetch files with incorrect hash using rpm module
  register: rpm_files_with_incorrect_hash
  changed_when: False
  check_mode: no
  tags:
    - CCE-27157-7
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)
    - NIST-800-53-SI-7(1)
    - NIST-800-171-3.3.8
    - NIST-800-171-3.4.1
    - DISA-STIG-RHEL-07-010020

- name: Verify File Hashes with RPM - Reinstall packages of files with incorrect hash
  shell: |
    yum reinstall -y $(rpm -qf '{{ item }}')
  args:
    warn: False # Ignore ANSIBLE0006, this task is flexible with regards to package manager
  loop: "{{ rpm_files_with_incorrect_hash.stdout_lines }}"
  when:
    - rpm_files_with_incorrect_hash.stdout_lines is defined
    - (rpm_files_with_incorrect_hash.stdout_lines | length > 0)
  tags:
    - CCE-27157-7
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)
    - NIST-800-53-SI-7(1)
    - NIST-800-171-3.3.8
    - NIST-800-171-3.4.1
    - DISA-STIG-RHEL-07-010020

# AIDE Tasks would go here

- name: Disable Prelinking - Check if Prelink File Exists
  stat:
    path: /etc/sysconfig/prelink
  register: prelink_file_exists
  check_mode: no
  tags:
    - CCE-27078-5
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)
    - NIST-800-53-SC-28
    - NIST-800-53-SI-7
    - NIST-800-171-3.13.11

- name: Disable Prelinking if Prelink File Exists
  lineinfile:
    path: /etc/sysconfig/prelink
    regexp: '^PRELINKING='
    line: 'PRELINKING=no'
  when:
    - prelink_file_exists.stat.exists is defined
    - prelink_file_exists.stat.exists
  tags:
    - CCE-27078-5
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)
    - NIST-800-53-SC-28
    - NIST-800-53-SI-7
    - NIST-800-171-3.13.11

- name: Ensure gpgcheck is Enabled for All yum Package Repositories - Find yum Repo files
  find:
    paths: "/etc/yum.repos.d/"
    patterns: "*.repo"
    contains: ^\[.+]$
  register: yum_repo_files_found
  check_mode: no
  tags:
    - CCE-26876-3
    - NIST-800-53-CM-5(3)
    - NIST-800-53-CM-11(a)
    - NIST-800-53-SI-7
    - NIST-800-53-MA-1(b)
    - NIST-800-171-3.4.8

- name: Ensure gpgcheck Enabled For All yum Package Repositories
  lineinfile:
    create: yes
    path: "{{ item.path }}"
    regexp: '(?i)^#?gpgcheck'
    line: "gpgcheck=1"
  loop: "{{ yum_repo_files_found.files }}"
  when: yum_repo_files_found.files is defined
  tags:
    - CCE-26876-3
    - NIST-800-53-CM-5(3)
    - NIST-800-53-CM-11(a)
    - NIST-800-53-SI-7
    - NIST-800-53-MA-1(b)
    - NIST-800-171-3.4.8

- name: Ensure GPG check Enabled for Local Packages (Yum)
  ini_file:
    create: yes
    path: /etc/yum.conf
    section: main
    option: localpkg_gpgcheck
    value: "1"
    no_extra_spaces: yes
  tags:
    - CCE-80347-8
    - NIST-800-53-CM-5(3)
    - NIST-800-53-CM-11
    - NIST-800-171-3.4.8
    - DISA-STIG-RHEL-07-020060

- name: Ensure YUM Removes Previous Package Versions
  ini_file:
    path: /etc/yum.conf
    section: main
    option: clean_requirements_on_remove
    value: 1
    no_extra_spaces: yes
  tags:
    - CCE-80346-0
    - NIST-800-53-SI-2(6)
    - NIST-800-53-CM-11
    - NIST-800-171-3.4.8
    - DISA-STIG-RHEL-07-020200

- name: Ensure GPG check is globally activated (yum)
  ini_file:
    dest: /etc/yum.conf
    section: main
    option: gpgcheck
    value: 1
    no_extra_spaces: yes
  tags:
    - CCE-26989-4
    - NIST-800-53-CM-5(3)
    - NIST-800-53-CM-11
    - NIST-800-53-SI-7
    - NIST-800-53-MA-1(b)
    - NIST-800-171-3.4.8
    - DISA-STIG-RHEL-07-020050
