---
# handlers file for centos7-cui-compliance

- name: Restart the sshd Service
  service:
    name: sshd
    state: restarted
  listen: restart sshd

- name: Restart the firewalld Service
  service:
    name: firewalld
    state: restarted
  listen: restart firewalld

- name: Reload the auditd service
  service:
    name: auditd
    state: reloaded
  listen: reload auditd

- name: Restart the auditd service
  service:
    name: auditd
    state: restarted
  listen: restart auditd
