---
# handlers file for centos7-cui-compliance

- name: Restart the sshd Service
  service:
    name: sshd
    state: restarted
  listen: restart sshd

- name: Restart the firewalld Service
  service:
    name: firewalld
    state: restarted
  listen: restart firewalld
